name: DeployAuto CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Deploy para o host
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH}}
          SOURCE: "code/"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: ${{ secrets.REMOTE_TARGET }}
      - name: Execute Bash start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{secrets.SERVER_SSH}}
          script: |
            cd ${{secrets.REMOTE_TARGET}}
            rm -R dist
            npm install
            npm run build
            pm2 delete gestao-financeita-api
            pm2 start --name "gestao-financeita-api" ${{secrets.REMOTE_TARGET}}/dist/main/server.js
            
