name: DeployAuto CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Deploy para o host
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH}}
          SOURCE: "code/"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          TARGET: ${{ secrets.REMOTE_TARGET }}
      - name: Execute Bash start
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{secrets.SERVER_SSH}}
          script: |
            cd ${{secrets.REMOTE_TARGET}}
            ls
            rm -R dist
            ls
            npm install
            npm run build
            pm2 delete manga-jj-api
            pm2 start --name "manga-jj-api" ${{secrets.REMOTE_TARGET}}/dist/main/server.js
            
